services:
  mongodb:
    container_name: mongodb
    image: mongo:8
    volumes:
      - vol-mongodb:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped

  api:
    container_name: gestao-de-estoque-api
    build:
      context: ../gestao-de-estoque-api
      dockerfile: Dockerfile
    environment:
      - DB_URL=mongodb://mongodb:27017/gerenciarEstoque
      - APP_PORT=5011
    ports:
      - "5011:5011"
    depends_on:
      - mongodb
    restart: unless-stopped

  frontend:
    container_name: gestao-de-estoque-front
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5011
      - NEXT_PUBLIC_ACCESS_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MDgwNmE2MGExMTQ3ZWU1Mzc5YmJmYSIsImlhdCI6MTc2MjE5ODAwNiwiZXhwIjoxNzYyMjg0NDA2fQ.N1Bu7XNr1w0Qd--DNOLB-PHCiNBwtXj37dbjPeVDG_E
      - NEXT_PUBLIC_SIMULAR_ERRO=false
      - API_URL_SERVER_SIDED=http://api:5011
      - NEXTAUTH_SECRET=gestao-estoque-secret-key-production-2025-secure-hash-jwt-auth
      - NEXTAUTH_URL=http://localhost:3000
    ports:
      - "3000:3000"
    depends_on:
      - api
    restart: unless-stopped

volumes:
  vol-mongodb:
